# Generated by Django 4.2.28 on 2026-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesstion',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggesstion',
            name='types',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('student', 'Student'), ('staff', 'Staff')], max_length=20),
        ),
    ]
